# Generated by Django 3.1.2 on 2021-04-08 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_handlemodel_searchresulthistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('claim_num', models.IntegerField()),
                ('claim_field', models.CharField(max_length=500)),
                ('Can_you_reproduce_this_claim', models.CharField(max_length=20)),
                ('source_Code', models.CharField(help_text='Enter the URL of your sourcecode', max_length=100)),
                ('datasets', models.CharField(help_text='Enter the URL of your dataset', max_length=100)),
                ('experiments_and_results', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
