# Generated by Django 3.1.2 on 2021-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_claimmodel_claim_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=500, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
