# Generated by Django 3.1.2 on 2021-04-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dislike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='users',
        ),
    ]
