# Generated by Django 3.1.2 on 2021-04-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210420_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
