# Generated by Django 3.1.2 on 2021-04-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_claimlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlikemodel',
            name='claimid',
            field=models.IntegerField(null=True),
        ),
    ]
