# Generated by Django 3.1.2 on 2021-04-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_claimlikemodel_claimid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimlikemodel',
            old_name='claimid',
            new_name='claim_id',
        ),
    ]
