# Generated by Django 3.1.2 on 2021-04-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210421_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimlikemodel',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
